### ISSUE TITLE
Suggestion/Request: 

### ISSUE THREAD

**Issue by AndrewStoddard** [pilar6195/AniList-Extras#14]
Similar to adding the Anilist Link to MAL, add it to https://animension.to/

I.E. Use the Anilist api to search for the name of the anime and get the url from that if it find it. 
https://animension.to/2417963969 Searches One Piece and the url would be the top result.

I am too lazy to do it myself. 😄

**Comment by pilar6195** [comment]
Few years late but probably won't do this since it's out of the scope of what the userscript/extension it meant to do.
